title: Daniel Kim | Cybersecurity Blog
description: Cybersecurity student sharing projects, technical notes, and learning experiences.

url: "https://santapower.github.io"
baseurl: ""

theme: minima

author:
  name: Daniel Kim

header_pages:
  - index.md
  - posts.md
  - about.md

github_username: YOUR-USERNAME

markdown: kramdown

plugins:
  - jekyll-feed

show_excerpts: true

minima:
  skin: dark
