title: Daniel Kim | Cybersecurity Blog
description: Cybersecurity student sharing projects, technical notes, and learning experiences.

url: "https://santapower.github.io"
baseurl: ""

theme: jekyll-theme-cayman

author:
  name: Daniel Kim

show_downloads: false

github:
  is_project_page: false
