title: Daniel Kim | Cybersecurity Blog
description: Cybersecurity student sharing projects, technical notes, and learning experiences.

url: "https://santapower.github.io"
baseurl: ""

author:
  name: Daniel Kim

github_username: YOUR-USERNAME

markdown: kramdown

plugins:
  - jekyll-feed

show_excerpts: true
